FROM node:18

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (melhora o cache)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# Inicia o servidor de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host"]
