
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=sgpg
    networks:
      - sgpg_network

  db:
    image: mysql:8.0
    container_name: mysql_sgpg
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgpg
    ports:
      - "3306:3306"
    networks:
      - sgpg_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

networks:
  sgpg_network:
    driver: bridge

volumes:
  mysql_data:
